/**
 * =====================================================
 *  works.js 작품 추가는 여기서만
 * =====================================================
 *  category 값:
 *    일러스트 > "commission" | "personal" | "commercial"
 *    애니메이션       → "2d-animation" | "3d-animation"
 *    낙서장   → "doodles"
 *    게임    > "game"
 *    캐릭터 > "character"
 *    order가 높을수록 최신
 *    
 *  태그 (선택):
 *    tags: ["fanart"]   ← 태그 필터에 표시됨
 *  
 * 이미지 경로:
 *    thumb:  "img/works/engname/thumb.jpg"
 *    video: "youtube:dQw4w9WgXcQ" // youtube.com/watch?v=dQw4w9WgXcQ <<이거 
 *    images: ["img/works/engname/01.jpg", ...]
 * =====================================================
 */

const WORKS = [
  {
    id: "work-1783932572777",
    category: "personal",
    title: "아다치 레이",
    title_en: "adachi rei",
    year: 2026,
    order: 1783932576222,     
    thumb: "img/works/work-1783932572777/01.webp",
    images: ["img/works/work-1783932572777/01.webp"],
    tags: ["fanart"],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783932524527",
    category: "cha-personal",
    title: "자캐",
    title_en: "OC",
    year: 2026,
    order: 1783932526597,     
    thumb: "img/works/work-1783932524527/01.webp",
    images: ["img/works/work-1783932524527/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783868404039",
    order: 1783868406428,
    category: "cha-personal",
    title: "제키",
    title_en: "jacky",
    year: 2026,
    thumb: "img/works/work-1783868404039/01.webp",
    images: ["img/works/work-1783868404039/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783868353349",
    order: 1783868355749,
    category: "cha-personal",
    title: "드리머의 드림랜드",
    title_en: "dreamer's dreamland",
    year: 2026,
    thumb: "img/works/work-1783868353349/01.webp",
    images: ["img/works/work-1783868353349/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783868327961",
    order: 1783868329664,
    category: "cha-personal",
    title: "효니",
    title_en: "hyoni",
    year: 2026,
    thumb: "img/works/work-1783868327961/01.webp",
    images: ["img/works/work-1783868327961/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783868298407",
    order: 1783868300738,
    category: "sketchbook",
    title: "선생님들",
    title_en: "teachers",
    year: 2026,
    thumb: "img/works/work-1783868298407/01.webp",
    images: ["img/works/work-1783868298407/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783868232898",
    order: 1783868235379,
    category: "cha-personal",
    title: "시계",
    title_en: "clock",
    year: 2026,
    thumb: "img/works/work-1783868232898/01.webp",
    images: ["img/works/work-1783868232898/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783868188251",
    order: 1783868190292,
    category: "cha-personal",
    title: "광대",
    title_en: "clown",
    year: 2026,
    thumb: "img/works/work-1783868188251/01.webp",
    images: ["img/works/work-1783868188251/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783867355748",
    order: 1783867359283,
    category: "cha-personal",
    title: "옥타비오",
    title_en: "octavio",
    year: 2026,
    thumb: "img/works/work-1783867355748/01.webp",
    images: ["img/works/work-1783867355748/01.webp","img/works/work-1783867355748/02.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783867326346",
    order: 1783867328859,
    category: "cha-personal",
    title: "사과",
    title_en: "apple",
    year: 2026,
    thumb: "img/works/work-1783867326346/01.webp",
    images: ["img/works/work-1783867326346/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783866614764",
    order: 1783866614764,
    category: "cha-personal",
    title: "귀여운 고양이",
    title_en: "cute cat",
    year: 2026,
    thumb: "img/works/work-1783866614764/01.webp",
    images: ["img/works/work-1783866614764/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "work-1783866480307",
    order: 1783866480308,
    category: "cha-personal",
    title: "집",
    title_en: "house",
    year: 2026,
    thumb: "img/works/work-1783866480307/01.webp",
    images: ["img/works/work-1783866480307/01.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "illu-000",
    order: 0,
    category: "personal",
    title: "토스트",
    title_en: "toast",
    year: 2021,
    thumb: "img/works/illust/0/0.webp",
    images: ["img/works/illust/0/0.webp"],
    tags: [],
    description: "블렌더 3D",
    description_en: "blender 3D",
  },
  {
    id: "illu-001",
    order: 1,
    category: "personal",
    title: "해질녘 거리",
    title_en: "Street at Sunset",
    year: 2026,
    thumb: "img/works/illust/1/1.webp",
    images: ["img/works/illust/1/1.webp"],
    tags: [],
    description: "해질녘, 그 거리에.",
    description_en: "At sunset, on that street.",
  },
  {
    id: "illu-002",
    order: 2,
    category: "personal",
    title: "숲 속 보물",
    title_en: "Treasure in the Forest",
    year: 2026,
    thumb: "img/works/illust/2/2.webp",
    images: ["img/works/illust/2/2.webp"],
    tags: [],
    description: "깊은 숲 속에서 찾아버린거야",
    description_en: "I found it deep in the forest.",
  },
  {
    id: "illu-003",
    order: 3,
    category: "personal",
    title: "따뜻한 아침",
    title_en: "Warm morning",
    year: 2026,
    thumb: "img/works/illust/3/3.webp",
    images: ["img/works/illust/3/3.webp"],
    tags: [],
    description: "따뜻한 주말 아침, 이 아침이 계속 되면 좋겠어",
    description_en: "On a warm weekend morning,I wish this morning could last forever.",
  },
  {
    id: "illu-004",
    order: 4,
    category: "personal",
    title: "재앙이 들이닥쳐도",
    title_en: "Even if disaster strikes",
    year: 2026,
    thumb: "img/works/illust/4/4.webp",
    images: ["img/works/illust/4/4.webp"],
    tags: [],
    description: "무서운 순간에도 둘이 있으면 괜찮을까",
    description_en: "Even in scary moments, will it be okay if we're together?",
  },
  {
    id: "illu-005",
    order: 5,
    category: "personal",
    title: "마트 유령",
    title_en: "Ghost of the Mart",
    year: 2026,
    thumb: "img/works/illust/5/5.webp",
    images: ["img/works/illust/5/5.webp"],
    tags: [],
    description: "내가 보인다면 손을 흔들어줘.",
    description_en: "If you see me, say hello.",
  },
  {
    id: "illu-006",
    order: 6,
    category: "personal",
    title: "바다를 달리는 열차",
    title_en: "A train racing across the sea",
    year: 2026,
    thumb: "img/works/illust/6/6.webp",
    images: ["img/works/illust/6/6.webp"],
    tags: [],
    description: "학교에 지각하면 안될텐데",
    description_en: "I really shouldn't be late for school",
  },
  {
    id: "illu-007",
    order: 7,
    category: "personal",
    title: "무서워하지마",
    title_en: "Don't be scared.",
    year: 2026,
    thumb: "img/works/illust/7/7.webp",
    images: ["img/works/illust/7/7.webp"],
    tags: [],
    description: "이 꽃을 너에게 줄게.",
    description_en: "I'll give you this flower.",
  },
  {
    id: "illu-008",
    order: 8,
    category: "personal",
    title: "더이상 못 올라가겠어!",
    title_en: "I can't climb any higher!",
    year: 2026,
    thumb: "img/works/illust/8/8.webp",
    images: ["img/works/illust/8/8.webp"],
    tags: [],
    description: "너도 참 운동 좀 하라니까!",
    description_en: "You really should exercise more!",
  },
  {
    id: "illu-009",
    order: 9,
    category: "personal",
    title: "이건 불공평해!",
    title_en: "it's Unfair!",
    year: 2026,
    thumb: "img/works/illust/9/9.webp",
    images: ["img/works/illust/9/9.webp"],
    tags: [],
    description: "아, 또 졌어!",
    description_en: "Ah, I lost again!",
  },
  {
    id: "illu-010",
    order: 10,
    category: "personal",
    title: "새벽의 다과회",
    title_en: "The Dawn Tea Party",
    year: 2026,
    thumb: "img/works/illust/10/10.webp",
    images: ["img/works/illust/10/10.webp"],
    tags: [],
    description: "맛있겠다, 정말 고마워!",
    description_en: "This looks delicious, thank you so much!",
  },
  {
    id: "illu-013",
    order: 13,
    category: "personal",
    title: "마녀의 외출",
    title_en: "The Witch's Outing",
    year: 2026,
    thumb: "img/works/illust/13/13.webp",
    images: ["img/works/illust/13/13.webp"],
    tags: [],
    description: "저 작은 빗자루를 타고 어딜 가는걸까",
    description_en: "Where could she be going on that little broomstick?",
  },
  {
    id: "illu-014",
    order: 14,
    category: "personal",
    title: "에일리언 미쿠",
    title_en: "alien miku",
    year: 2026,
    thumb: "img/works/illust/14/14.webp",
    images: ["img/works/illust/14/14.webp"],
    tags: ["fanart"],
    description: "에일리언 미쿠 팬아트!",
    description_en: "alien miku fanart!",
  },
  {
    id: "illu-015",
    order: 15,
    category: "personal",
    title: "어메이징 디지털 서커스 팬아트",
    title_en: "The amazing digital circus fanart",
    year: 2026,
    thumb: "img/works/illust/15/15.webp",
    images: ["img/works/illust/15/15.webp"],
    tags: ["fanart"],
    description: "어메이징 디지털 서커스 팬아트!",
    description_en: "The amazing digital circus fanart!",
  },
  {
    id: "illu-016",
    order: 16,
    category: "personal",
    title: "호수 안에",
    title_en: "In the lake",
    year: 2026,
    thumb: "img/works/illust/16/16.webp",
    images: ["img/works/illust/16/16.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "commi-001",
    order: 11,
    category: "commission",
    title: "커미션_260310",
    title_en: "Commission_260310",
    year: 2026,
    thumb: "img/works/illust/11/11.webp",
    images: ["img/works/illust/11/11.webp"],
    tags: [],
    description: "캐릭터+배경 커미션",
    description_en: "character+background commission",
  },
  {
    id: "commi-002",
    order: 12,
    category: "commission",
    title: "커미션_260311",
    title_en: "Commission_260311",
    year: 2026,
    thumb: "img/works/illust/12/12.webp",
    images: ["img/works/illust/12/12.webp"],
    tags: [],
    description: "캐릭터+배경 커미션",
    description_en: "character+background commission",
  },
  {
    id: "anim-001",
    order: undefined,
    category: "2d-animation",
    title: "컬트 오브 더 램 팬애니메이션",
    title_en: "cotl fan mv",
    year: 2024,
    thumb: "img/works/2Danim/nakama/thumb.webp",
    images: [""],
    tags: ["fanart"],
    description: "",
    description_en: "",
  },
  {
    id: "anim-002",
    order: undefined,
    category: "3d-animation",
    title: "루프 더 룸 팬애니메이션",
    title_en: "looping the rooms fan mv",
    year: 2026,
    thumb: "img/works/3Danim/looptheroom/thumb.webp",
    images: [""],
    tags: ["fanart"],
    description: "",
    description_en: "",
  },
  {
    id: "game-001",
    order: undefined,
    category: "game",
    title: "엘스웨어",
    title_en: "ElseWhere",
    year: 2026,
    thumb: "img/works/game/1/1.webp",
    images: ["img/works/game/1/1-2.webp"],
    tags: [],
    description: "엘스웨어 프로토타입 개발",
    description_en: "ElseWhere prototype dev",
  },
  {
    id: "chara-001",
    order: 1,
    category: "cha-personal",
    title: "무제",
    title_en: "Untitled",
    year: 2026,
    thumb: "img/works/chara/1/1.webp",
    images: ["img/works/chara/1/1.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "chara-002",
    order: 2,
    category: "cha-personal",
    title: "네명의 보스들",
    title_en: "four bosses",
    year: 2026,
    thumb: "img/works/chara/2/2.webp",
    images: ["img/works/chara/2/2.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "chara-003",
    order: 3,
    category: "cha-personal",
    title: "아이들",
    title_en: "children",
    year: 2026,
    thumb: "img/works/chara/3/3.webp",
    images: ["img/works/chara/3/3.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "chara-004",
    order: 4,
    category: "cha-personal",
    title: "오리지널 캐릭터1",
    title_en: "OC",
    year: 2026,
    thumb: "img/works/chara/4/4.webp",
    images: ["img/works/chara/4/4.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "chara-005",
    order: 5,
    category: "cha-personal",
    title: "로봇",
    title_en: "robot",
    year: 2026,
    thumb: "img/works/chara/5/5.webp",
    images: ["img/works/chara/5/5.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "chara-006",
    order: 0,
    category: "cha-personal",
    title: "비와 퍼피캣",
    title_en: "bee and puppy cat",
    year: 2021,
    thumb: "img/works/chara/6/6.webp",
    images: ["img/works/chara/6/6.webp"],
    tags: ["fanart"],
    description: "",
    description_en: "",
  },
  {
    id: "chara-007",
    order: 0,
    category: "cha-personal",
    title: "나,조립법",
    title_en: "Me, Build Guide",
    year: 2021,
    thumb: "img/works/chara/7/7.webp",
    images: ["img/works/chara/7/7.webp","img/works/chara/7/7-1.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "chara-008",
    order: 6,
    category: "cha-personal",
    title: "효니",
    title_en: "hyoni",
    year: 2026,
    thumb: "img/works/chara/8/8.webp",
    images: ["img/works/chara/8/8.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "chara-009",
    order: 7,
    category: "cha-personal",
    title: "버디",
    title_en: "BUDDY",
    year: 2026,
    thumb: "img/works/chara/9/9.webp",
    images: ["img/works/chara/9/9.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "doodle-001",
    order: 0,
    category: "sketchbook",
    title: "애니메이션 습작",
    title_en: "Animation Practice",
    year: 2026,
    thumb: "img/works/doodles/1/1.webp",
    images: ["img/works/doodles/1/1-1.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "doodle-002",
    order: 1,
    category: "sketchbook",
    title: "캐릭터낙서1",
    title_en: "charaDoodle",
    year: 2026,
    thumb: "img/works/doodles/2/2.webp",
    images: ["img/works/doodles/2/2.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "doodle-003",
    order: 2,
    category: "sketchbook",
    title: "캐릭터낙서2",
    title_en: "charaDoodle2",
    year: 2026,
    thumb: "img/works/doodles/3/3.webp",
    images: ["img/works/doodles/3/3.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "doodle-004",
    order: 3,
    category: "sketchbook",
    title: "캐릭터낙서3",
    title_en: "charaDoodle3",
    year: 2026,
    thumb: "img/works/doodles/4/4.webp",
    images: ["img/works/doodles/4/4.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "doodle-005",
    order: 4,
    category: "sketchbook",
    title: "캐릭터낙서4",
    title_en: "charaDoodle4",
    year: 2026,
    thumb: "img/works/doodles/5/5.webp",
    images: ["img/works/doodles/5/5.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "doodle-006",
    order: 5,
    category: "sketchbook",
    title: "캐릭터낙서5",
    title_en: "charaDoodle5",
    year: 2026,
    thumb: "img/works/doodles/6/6.webp",
    images: ["img/works/doodles/6/6.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "doodle-007",
    order: 6,
    category: "sketchbook",
    title: "캐릭터낙서6",
    title_en: "charaDoodle6",
    year: 2026,
    thumb: "img/works/doodles/7/7.webp",
    images: ["img/works/doodles/7/7.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
  {
    id: "doodle-008",
    order: 7,
    category: "sketchbook",
    title: "캐릭터낙서7",
    title_en: "charaDoodle7",
    year: 2026,
    thumb: "img/works/doodles/8/8.webp",
    images: ["img/works/doodles/8/8.webp"],
    tags: [],
    description: "",
    description_en: "",
  },
];
